# Generated by Django 4.1.7 on 2023-02-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=50)),
                ('q2', models.CharField(max_length=50)),
                ('q3', models.CharField(max_length=50)),
                ('q4', models.CharField(max_length=50)),
                ('q5_1', models.CharField(max_length=50)),
                ('q5_2', models.CharField(max_length=50)),
                ('q6', models.CharField(max_length=200)),
                ('q7', models.CharField(max_length=50)),
                ('q8', models.CharField(max_length=50)),
                ('q9', models.CharField(max_length=50)),
                ('q10', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '설문결과',
                'verbose_name_plural': '설문결과',
                'db_table': 'survey_result',
            },
        ),
    ]
